### ISSUE TITLE
sample.ipynb demo no longer works

### ISSUE THREAD

**Issue by vitruvi** [ustc-bmec/Whole-Brain-Conv#6]
The demo fmri image and sample.ipynb file produce a wrong result at the moment.

Currently, I get the probability below, when i decode the file you provided in the repository with sample.ipynb notebook:
tensor([[0.0037, 0.2303, 0.0036, 0.0065, 0.0014, 0.0768, 0.6778]],  device='cuda:0') # top probability is the last class and wrong.

I use nibabel 4.0.1, pytorch 1.8.2 and cuda 11.4

But on github, the sample.ipynb file gives the probability result below, which is the correct one:
tensor([[6.1537e-09, 1.0000e+00, 5.6260e-11, 2.5552e-15, 6.2870e-09, 4.2733e-11, 6.1202e-08]], device='cuda:0') # top probability is the second class.

Can you please help me solve this problem? This is crucially important for me.

I had reproduced your results previously, that code also no longer works. I couldn't find a solution.

To reproduce the issue:
- clone the repository
- run sample.ipynb
- observe the "pred_prob" output.

**Comment by ustc-bmec** [comment]
I tried the code in the server, and it reported the same result with yours, the wrong result.
But we have checked the codes when we uploaded them 3 years ago.
It looks like that there is something wrong with loading the checkpoint, which may be due to the compatibility problem.
So need to train a new model if you want to use it.
But my suggestion is to use the [fMRI-Conv-Att](https://github.com/ustc-bmec/fMRI-Conv-Att) instead.

**Comment by vitruvi** [comment]
I think there is a bigger problem than just loading the checkpoint. I had reproduced the code for this project 2 years ago. But, now, its accuracy is extremely low when I train it from scratch at the moment. I have tried a lot of pytorch-cuda versions for backward compatibility and it didn't work. It might also be due to a change in NiBabel or numpy.

If only we knew the initial environment as a requirements.txt file.

I have used the reproduced project in my thesis but I cannot reproduce it again at the moment. Sad situation.

It is going to be a huge relief, if you can help me find the compatibility problem in this project.

**Comment by ustc-bmec** [comment]
The issue may be due to the normalization step in dataloading.
I changed the line 26 of dataset.py from `data = data / data.max(axis=3)[:, :, :, np.newaxis]` to 
`data = data / np.amax(data)`
,then the model worked and returned 
tensor([[0.0030, 0.0339, 0.0057, 0.6274, 0.0115, 0.2143, 0.1042]], device='cuda:0').

**Comment by vitruvi** [comment]
The value in sample.ipynb is "tensor([[6.1537e-09, 1.0000e+00, 5.6260e-11, 2.5552e-15, 6.2870e-09, 4.2733e-11,
         6.1202e-08]], device='cuda:0')". The change you propose changes the normalization from timepoint-wise to global, a different function.

**Comment by ustc-bmec** [comment]
It looks like that the value in sample.ipynb might be from another input, for the label of './119833_Motor_1_lh.nii.gz' is [0,0,0,1,0,0,0].
